### PR TITLE
fix importing owner-less Var/MVar types

### PR DESCRIPTION
**Pull request by tailsu**
Fix the crash when `new GenericParameter(position, type, module)`, which creates an ownerless generic parameter, is then `module.Import()`'ed (or any type reference using referencing it internally).

### CODE REVIEW

**Comment by jbevain** [comment]
That looks good, thanks! Any chance you can add a Import test so we don't regress here?

**Comment by tailsu** [comment]
You got it :)

**Comment by tailsu** [comment]
ping?

**Comment by jbevain** [comment]
Hey @tailsu,

Sorry for the delay processing this.

I've had a look at the test case, and it makes me wonder if the fix is correct.

The reason is that you're trying to import a reference to a (open) generic instantiation, instantiated with a generic argument that is a generic parameter that has no parent. Which shouldn't be legal.

There's no real reason for this to happen, and if we shouldn't throw a pesky NRE, we shouldn't fallback to importing a reference that doesn't make sense in the Cecil type system.

Now I'm curious as to what triggered this. Is this actual code that you're running?

**Comment by tailsu** [comment]
It's close to my actual code. In my actual code I emit a `ldtoken` with this type (essentially `ldtoken IEnumerable<!0>`) in a method in a type with a generic argument.  My understanding is that owner-less `GenericParameter` instances are used to refer to the generic arguments in context (`!0`, `!!0`, etc.).

**Comment by jbevain** [comment]
Nope :) We shouldn't have a GenericParameter without a DeclaringType or a DeclaringMethod.

It depends what you try to have. In your case, if you want an open instantiation of IEnumerable`1 you could write:

```csharp
	var openEnumerable = module.Import (typeof (IEnumerable<>));
	var instanceEnumerable = new GenericInstanceType (openEnumerable);
	instanceEnumerable.GenericArguments.Add (openEnumerable.GenericParameters [0]);
```

Makes sense?

**Comment by tailsu** [comment]
I have:
```
public class C<T>
{
public RuntimeTypeHandle M()
{
return typeof(IEnumerable<T>).RuntimeMethodHandle;
}
}
```
I implement the return using `ldtoken class IEnumerable<!0>`, where the metadata signature of the type is `GenericInst Class IEnumerable`1 Var!0`. In this situation it makes no sense to have a named generic parameter, because Var!0 makes sense _in context_. It also works correctly at runtime and produces no PEVerify errors.

I construct the type using
```
var openEnumerable = module.Import (typeof (IEnumerable<>));
var instanceEnumerable = new GenericInstanceType (openEnumerable);
var T = new GenericParameter (0, genericParameterType, module); // Var!0
instanceEnumerable.GenericArguments.Add (T);
```

Now, from Cecil's standpoint, I could take the first generic parameter of C<T> and add that to `instanceEnumerable.GenericArguments`, but either way should be equally valid, I think.

**Comment by jbevain** [comment]
For this, yes, you need to take T from C, as we maintain a coherent object model where you can expect to know who declared a GenericParameter.

We probably shouldn't expose this constructor :)

**Comment by tailsu** [comment]
Bummer...

**Comment by jbevain** [comment]
Sorry, thanks for the PR though :)

**Pull request closed without merging**
