### PR TITLE
Fix ReadSymbols in a Module that is already created

### PR DESCRIPTION
**Pull request by thaystg**
When I try to use ReadSymbols in a Module that is already created, for example:

```
var symbolReader = portablePdbReaderProvider.GetSymbolReader(asm.image, stream);
asm.image.ReadSymbols(symbolReader);
```

method.debug_info has a list, but it's empty, so it wasn't entering in the if, but it should, maybe we should change the if to method.debug_info == null || method.debug_info.count = 0.

Relates to this PR: https://github.com/dotnet/runtime/pull/40690

### CODE REVIEW

**Comment by jbevain** [comment]
Hi @thaystg, good to see you here.

Could you add a unit test that reproduces your scenario?

**Comment by thaystg** [comment]
> Hi @thaystg, good to see you here.
> 
> Could you add a unit test that reproduces your scenario?

Done!!! :)

**Comment by thaystg** [comment]
@jbevain could you please merge and generate a new nuget version? We need this for wasm debug.

**Comment by jbevain** [comment]
Thanks!

**Comment by jbevain** [comment]
@thaystg the fix shipped in 0.11.3. Thanks!

**Pull request merged**
