### PR TITLE
Winrt projections

### PR DESCRIPTION
**Pull request by ignas2**

### CODE REVIEW

**Comment by TautvydasZilys** [comment]
Hey jb, is there any chance you forgot about this PR?

**Comment by jbevain** [comment]
@TautvydasZilys @ignas2 hey folks. I finally have some time to go over this.

Overall it looks pretty good, but there's zero tests. Please add tests :)

**Comment by TautvydasZilys** [comment]
@jbevain I wasn't exactly sure how cecil is usually tested, here's my stab at it:

https://github.com/Unity-Technologies/cecil/commit/eeefa4aa986cb41863fa90bc604382296b0369f7

If you think that's good enough, I'll go ahead and update the PR. Otherwise, let me know what else I must add.

**Comment by jbevain** [comment]
@TautvydasZilys Cecil has a strong focus on its integration test suite.

Any chance you could make your tests reuse the existing test suite mechanism? We want to make sure we can read and also write winmdb files correctly.

**Comment by TautvydasZilys** [comment]
@jbevain could you close this PR? I made a new one from Unity-Technologies@39f1c03.

**Pull request closed without merging**
