### PR TITLE
failing test for no root

### PR DESCRIPTION
**Pull request by SimonCropp**
replaces https://github.com/Fody/Fody/issues/313

### CODE REVIEW

**Comment by SimonCropp** [comment]
@jbevain seems empty string is a valid scenario for PdbScope.usedNamespaces

so is this as easy as...?
```
foreach (var used_namespace in scope.usedNamespaces) {
	if (used_namespace == string.Empty) {
		continue;
	}
```

image

**Comment by SimonCropp** [comment]
@jbevain i know u r busy. but any chance u could review this?

**Comment by jbevain** [comment]
Could you upload a dll+pdb that I can have a look at?

**Comment by SimonCropp** [comment]
they are in this PR.  https://github.com/SimonCropp/cecil/blob/a8a573eff25a68cdc1b1444a79a537ac5b1412c4/Test/Resources/assemblies/NoRoot.dll and pdb

**Comment by jbevain** [comment]
Ah my bad! I'll try having a look today.

**Comment by SimonCropp** [comment]
thanks

**Comment by jbevain** [comment]
Thanks, I'm closing this in favor of #414.

**Comment by SimonCropp** [comment]
@jbevain cool. glad my PR helped point in the right direction.

**Pull request closed without merging**
