### PR TITLE
PCL version of Mono.Cecil

### PR DESCRIPTION
**Pull request by jbevain**
The plan for this is as follows:

* Ship a PCL for Mono.Cecil.dll only.
* Get rid of the explicit support for old frameworks (CF, SL, net_2_0).
* On a «desktop» .NET, have Mono.Cecil and other assemblies require at least net_3_5.
* All non desktop platforms must use the PCL version.

### CODE REVIEW

**Comment by oznetmaster** [comment]
Not sure why it is assumed that PCL is a replacement for CF, because it isn't.

There really needs to still be a CF build.  It is widely used in the CF community.

**Comment by rprouse** [comment]
@jbevain, do you know when you are planning on releasing a new NuGet package with these changes?

**Comment by CharliePoole** [comment]
@jbevain I'm a little confused. This PR appears to have been closed without merging. So what's the current status of .NET 2.0 and PCL and what do you plan?

**Comment by rprouse** [comment]
At least the nuget package changes are in master

**Comment by jbevain** [comment]
@rprouse, @CharliePoole Hi folks!

The PR has been merged in master, and the remote branch deleted, which is probably why GitHub is confused. I don't have an ETA for when I'll ship a new nuget as I'm slowly getting back on the saddle after moving halfway through the globe.

I've pinged our group in May about this change: https://groups.google.com/forum/#!topic/mono-cecil/5YGawO-YAZs

I suggest you join the group as it's low volume and gives you a chance to react when I post heads up.

**Comment by SimonCropp** [comment]
@jbevain would u like some help getting cecil setup on https://www.appveyor.com/

**Comment by jbevain** [comment]
@SimonCropp it's on AppVeyor: https://ci.appveyor.com/project/jbevain/cecil

**Comment by SimonCropp** [comment]
but no artifacts. would u prefer me to raise a new issue for this conversation?

**Comment by jbevain** [comment]
@SimonCropp yes please, thanks!

**Pull request closed without merging**
