### PR TITLE
Add support for the .NET Core profile

### PR DESCRIPTION
**Pull request by jbevain**

### CODE REVIEW

**Comment by eByte23** [comment]
@jbevain Keen for rc2 version of this

**Comment by jasonwilliams200OK** [comment]
@jbevain, will this land at https://www.nuget.org/packages/Mono.Cecil/ anytime soon? Thanks for the .NET Core support! :)

**Comment by jbevain** [comment]
@jasonwilliams200OK yes, http://cecil.pe/post/149243207656/mono-cecil-010-beta-1 :)

**Comment by jasonwilliams200OK** [comment]
Thanks! :tada:

**Pull request merged**
