### PR TITLE
Fix docid member name generic characters.

### PR DESCRIPTION
**Pull request by joelmartinez**
See #528 for details on this fix

### CODE REVIEW

**Comment by jbevain** [comment]
Getting a test failure:

```
Errors and Failures:
351) Test Failure : Mono.Cecil.Tests.DocCommentIdTests.EII
36     String lengths are both 84. Strings differ at index 15.
37  Expected: "M:N.X.N#IX{N#KVA{System#String,System#Int32}}#IXA(N#KVA{Syste..."
38  But was:  "M:N.X.N#IX{N#KVP{System#String,System#Int32}}#IXA(N.KVP{Syste..."
39
```

**Comment by joelmartinez** [comment]
@jbevain there it goes :) looks like the appveyor build passed, but the travis-ci build is still failing with what seems to be an unrelated issue?

```
NU1102: Unable to find package Microsoft.NETCore.App with version (>= 4.0.0)
```

**Comment by jbevain** [comment]
Yeah travis has been dead for a while.

**Comment by jbevain** [comment]
Thank you for your contribution!

**Comment by joelmartinez** [comment]
@jbevain I see ... ok, if there's a list, or a queue that I can get on to have this included, please consider this `.Push` :P Thanks!

**Pull request merged**
