### PR TITLE
Fix reading broken MDBs emitted by mcs. If sequence point ends at row…

### PR DESCRIPTION
**Pull request by mrvoorhe**
… -1, assume that the sequence point is just for a single line.

### CODE REVIEW

**Comment by mrvoorhe** [comment]
Test failure fixed.  The expected result has been updated.  Now the expected results match the expected results of the `PdbTests`.  The `-1` in the MdbTests was always wrong.

**Comment by jbevain** [comment]
Shouldn't this be dealt with client side?

If we're reading `6:-1:-1:-1`, we're going to write back `6:6:-1:-1` no?

**Comment by mrvoorhe** [comment]
I'll check with @TautvydasZilys who originally made the change and get back to you.  Thanks for taking a look.

**Comment by mrvoorhe** [comment]
@jbevain that's a good point.  After talking with @TautvydasZilys we are just going to drop this change.  We don't use mcs anymore so we'll be fine without this fix going forward.

**Pull request closed without merging**
