### PR TITLE
Recognize netstandard as a core library.

### PR DESCRIPTION
**Pull request by erozenfeld**

### CODE REVIEW

**Comment by erozenfeld** [comment]
@jbevain PTAL

**Comment by ericstj** [comment]
/cc @terrajobst @weshaggard
LGTM

**Comment by jbevain** [comment]
Thanks, I fixed it slightly differently in the commit mentioned above.

**Comment by terrajobst** [comment]
How do you detect the core assembly? Lookup by names have a tendency to be fragile and not to work very well when you inspect mixed-cases that involves facades. Ideally, you'd detect it by assuming the core assembly is the one without dependencies.

**Comment by jbevain** [comment]
The diff mentioned previously has all the details: Name + empty AssemblyRef table.
Jb, on a phone.
		

		
	_____________________________

**Pull request closed without merging**
